# Generated by Django 4.2.5 on 2026-01-19 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('srt_content', models.TextField(blank=True, null=True)),
                ('processed_video_file', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
